### ISSUE TITLE
Safari v5.0.3 (Win7) - First Load + No Display

### ISSUE THREAD

**Issue by daveGamache** [zurb/orbit#1]
Unconfirmed: There is a problem with the plugin on first load in the navigator "Safari v5.0.3" (Win7 machine, cache and coocki clean before launch) : there is no display. Apparently can even be seen on the playground page on ZURB.com.

**Comment by marianposaceanu** [comment]
same problem on chrome 9
- the fix is simple: you either (pre)set the width and height of the images
- or modify the script to wait for the images to load so that it can get the correct sizes and not null

**Comment by mkelly12** [comment]
Like dakull said, the workaround is to not load Orbit until window.load fires, however is for some reason you cannot wait for window.load I added a change that delays the load of orbit until all the image slides have loaded.
26e3946947965e9b383d6defd4e5f9e1cd429289
