### ISSUE TITLE
Dynamic content (start / stop plugin option?)

### ISSUE THREAD

**Issue by gonys** [zurb/orbit#16]
Does this plugin supports dynamic content? I have a problem with changing the code in a div and start with new contents. Please help.

**Comment by mkelly12** [comment]
Orbit does not currently work with dynamic content. When it first loads it looks at it's content and automatically determines what size it should be. The method for this detection is not current exposed.

If you want to share an example of how you would use Orbit with dynamic content, we might be able to expose a method or event you can trigger to fire to resizing of Orbit.
