### ISSUE TITLE
Preload not working with content

### ISSUE THREAD

**Issue by atlelill** [zurb/orbit#18]
I can't get the preloading to work with content-slides, only pure image-slides... With content-slides, the images don't show up at all, the loading.gif runs forever, and all the other content (h1's and intro-texts) are stacked on top of each other.

**Comment by mkelly12** [comment]
We have a new version of Orbit with improved load detection, can you try using the updated version to see if it fixes your problem?

https://github.com/zurb/orbit/blob/refactor/jquery.orbit-1.3.0.js
