### ISSUE TITLE
Caption animation

### ISSUE THREAD

**Issue by ooloth** [zurb/orbit#3]
Great plugin! Wondering if you could add a tiny featured that would animate a caption out the same way that it animates in. At the moment, it slides in so beautifully, but then simply sticks if when going to consecutive images with captions. I'd like the option to have each caption animate out to allow the next caption to animate in when on the image slide.

Thanks!

Michael

**Comment by mkelly12** [comment]
This feature was added a while back, but we forgot to close this issue. Closing it now.

**Comment by husainhk** [comment]
Hi, I am using version 1.2.3 and can't get the caption out animation to work. Is there another option apart from captionAnimation?

Cheers,
Husain

**Comment by badkinsATX** [comment]
I've been able to achieve something like this using the below code. I'm still trying to figure out how to have the html update after a fadeOut.

```
    this.$caption
      .attr('id', captionLocation) // Add ID caption TODO why is the id being set?
      .html(captionHTML).hide().delay(1000).fadeIn(1000); // Change HTML in Caption
```
