### ISSUE TITLE
Captions are not displayed

### ISSUE THREAD

**Issue by Tetriz** [zurb/orbit#32]
Hi,

can't get captions working. Doing everything like it is written here: http://www.zurb.com/playground/jquery_image_slider_plugin

It doesn't display any caption.

I'm also a bit confused, as on your home page the parameter captions: true is not used while in documentation it is described. I've tried both: with and w/o. 

Checked with firebug and noticed that generated by javascript <div class="orbit-caption"></div> is just empty.

So the content of the [<span id="htmlCaption" class="orbit-caption">I'm A Badass Caption: I can haz</span>] is not fetched into the div.

Am I doing something wrong?

Thank you.

**Comment by cpres** [comment]
You're not the only one. I have yet to figure out how the caption works for this slideshow yet as well.

**Comment by ghost** [comment]
I'm having the same problem. I noticed that div class="orbit-caption" is there all the time (but invisible) even if you don't type span captions as indicated. And when you do add span for captions it also becomes invisible.

**Comment by ghost** [comment]
the problem was in version of jQuery. You have to use jquery 1.5.1 or later..

**Comment by Tetriz** [comment]
Oh, cool! Thank you for update.

**Comment by kaspar-allenbach** [comment]
Hi.
Same for me. The caption div appears but is still hidden with display:none from .orbit-caption

I use jQuery 1.6.4

What can I do?

**Comment by cpres** [comment]
I got it working but I switched over to the orbit-1.3.0.js.

On 21 November 2011 06:24, Seppentoni <
reply@reply.github.com

**Comment by kaspar-allenbach** [comment]
I just don't get it.

Here is the site: http://www.drehmomentproduktion.ch/baustelle/
Captions just doesn't work and I don't understand why :( It's all there

**Comment by cpres** [comment]
You are running into two different javascript errors on your site
$(".container").fitVids();

and imagesLoaded both seem to be having problems.

I also don't see where your orbit.js is being loaded

On 23 November 2011 08:51, Seppentoni <
reply@reply.github.com

**Comment by kaspar-allenbach** [comment]
Okay. I now deleted all unrelated js
and embeded jquery 1.7.0 and Orbit 1.3.0 properly I guess.

It doesn't work. What am I doing wrong?

**Comment by kaspar-allenbach** [comment]
I found the Mistake. I wrapped the images into an "a" Tag linking to it's entry. Obviously captions doesn't like this.
