### ISSUE TITLE
Is there a way to add another element as the next or previous buttons?

### ISSUE THREAD

**Issue by darrellmfrench** [zurb/orbit#39]
I have a project where i am using Orbit as a survey. The client is asking if i could also enable another element to trigger the next slide function. If so, where do I go to do this?

**Comment by mkelly12** [comment]
I've just made a change in our refactor branch that allows you to shift the active slide by triggering an event on the original orbit element you added. a1a7fb79df407d55c33b087c7c0b0e7c4af620e8

``` javascript
$('#yourOrbitElement').trigger('orbit.next');
$('#yourOrbitElement').trigger('orbit.prev');
```

**Comment by dallasbpeters** [comment]
Any way to link to a specific slide? rather than just prev and next.
