### ISSUE TITLE
Gettin the arrows out of box

### ISSUE THREAD

**Issue by mcbloody** [zurb/orbit#45]
Hi everyone!

I love you plugin, so thanks for the time spent on it :)

I have been looking in vain at trying to get the arrows that move the slides left and right to the side of the box rather then on the inside (it says you can in one of the pre-loaded slides).

Can anyone help?

Thanks,
Eliott

**Comment by tehwebmaster** [comment]
Open the orbit css file
Find div.slider-nav {              // I think it's near 140 // 
Change 
display: block }
to 
display: none }

That's it!

**Comment by mcbloody** [comment]
hi tehwebmaster!

thanks very much! i've played around with it and got the effect I wanted :)

Cheers thanks again for your time.
Eliott

**Comment by tehwebmaster** [comment]
Not a problem Eliott
Glad I could help you out.
