### ISSUE TITLE
Start on specific slide

### ISSUE THREAD

**Issue by darrellmfrench** [zurb/orbit#47]
Is there a way to start the activeSlide on a certain slide from outside of the orbit.1.2.3.js? I want to make activeSlide a global variable and pass it a value from another part of the script

**Comment by mkelly12** [comment]
Using our new refactor branch you can trigger the `orbit.goto` event to jump to a slide at a particular index.

``` javascript
$('yourSliderId').trigger('orbit.goto', 3); // Jump to the forth slide (index 3)
```

You can run this code after `window.load` to jump to your starting slide.

**Comment by k3v3n** [comment]
I'm trying to do the same thing with F5, but it doesn't work. Still looking for a solution.
