### ISSUE TITLE
Images in content sliders

### ISSUE THREAD

**Issue by byalextran** [zurb/orbit#5]
I'm using Orbit to cycle through some content sections which include images. 

The problem I'm running into is those content sections display as two slides with Orbit. 

One slide being the content section itself (with image and any additional content). The second slide is just the image. 

Here's my markup.

```
<div id="features">
    <div class="feature">
        <img width="919" height="279" src="image1.jpg"> 
        <p><span class="didot">Title</span> <br> Subtitle</p>
    </div>
    <div class="feature">
        <img width="919" height="279" src="image2.jpg"> 
        <p><span class="didot">Title</span> <br> Subtitle</p>
    </div>
</div>
```

It appears like Orbit grabs any image within the containing div and uses it as a slide. Unfortunately, this method grabs images within content slides as well. 

Is it possible to update Orbit so that it excludes these images?

**Comment by suciuvlad** [comment]
The img inside the div.feature tag is as wide as the orbit wrapper. Therefore it pushes the content(title and subtitle) below. The wrapper has an overflow:hidden; applied to it. That gives you the impression that the image is used as a slide when in fact it's not.

**Comment by mkelly12** [comment]
**suciuvlad** is right, we're using `$.fn.children()` to select the image tags, so it will not traverse to nested images on the slides.

``` javascript
this.$slides = this.$element.children('img, a, div');
```
