### ISSUE TITLE
Console.Log statements break orbit

### ISSUE THREAD

**Issue by dotnetchris** [zurb/orbit#6]
Line 56: console.log(slides)

This will blow up and cause orbit to not work when Firebug is either closed in Firefox or completely break IE.

I would recommend implementing the solution found at http://digitalize.ca/2010/04/javascript-tip-save-me-from-console-log-errors/ to prevent this error from affecting clients.

**Comment by daveGamache** [comment]
Hey - 

Thanks for the note - we removed this immediately :) This was an accidental line that found its way into deployment. 

Woot
Dave
