### ISSUE TITLE
Content-only orbit failure.

### ISSUE THREAD

**Issue by rockinghelvetica** [zurb/orbit#8]
When there are zero images in the container's rotation, the container's dimensions get set to 1px by 1px in error.

**Comment by mkelly12** [comment]
**rockinghelvetica**: Right, the default state before it automatically resizes to the largest content slide is 1px by 1px. You can work around this by putting in a blank slide with the desired dimensions.

I am curious to know how you are using Orbit, and why you would not have any slides. Also what the correct behavior would be in your case.
