### ISSUE TITLE
Pause on load

### ISSUE THREAD

**Issue by formermember** [zurb/orbit#93]
Is there any way to have the slider NOT auto play?

Thanks

S

**Comment by rememberlenny** [comment]
This is so old, but I found a solution.

When you activate your slider, make a callback that clicks the "pause" button. This isn't the best solution, but it works great.

My code looks like this:

```
$('#case-sliders').foundation('orbit', {  stack_on_small: false, animation_speed: 750, bullets: false, bullets: true, }, function (response) {
     $('#case-sliders').find('.orbit-timer span').click();
})
```

In my case, the `#case-sliders` selector is activated with `.foundation('orbit',{ ... })`. The JSON contents are the specific attributes for my slider. Then at `function (response) {` I created a jquery selector to find the `span` button in the `.orbit-timer` div. 

By setting a `.click()` on this element, it stops the slider on load.

Will someone close this ticket? @arthurzurb @cmwinters @elledesgner @mhayes @NealKemp
